name = "koala-page"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "koala-db"
database_id = "placeholder"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "koala-images"
